on: workflow_dispatch
name: 1 Deploy Azure App Service (Bicep)

env:
  AZURERG: llm-iac-armlab2
  AZUREREGION: eastus

jobs:
  create-azure-rg:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0 # Optional
          inlineScript: |
            az group create --location $AZUREREGION -n $AZURERG
            
  appservice-bicep-template-deploy:
    if: ${{ success() }}
    needs: create-azure-rg
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep template
    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURERG }}
        template: ./IaC/deploy-appservice.bicep
        # parameters: appName=<Type a unique name for yor webapp>
        parameters: ./IaC/parameters-appservice.json
